=== diretto/JavaClientProcessingPlugin/conf/org/diretto/api/client/external/processing/config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="api-version" type="xs:string" />
				<xs:element name="service-class" type="xs:string" />
				<xs:element name="restlet-client">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="connector-protocol" type="xs:string" />
							<xs:element ref="connector-parameters" minOccurs="0" maxOccurs="1" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="connector-parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="parameter" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required" />
						<xs:attribute name="value" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== diretto/JavaClientProcessingPlugin/conf/org/diretto/api/client/external/processing/config.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">

	<name>org.diretto.api.external.processing</name>
	<api-version>v2</api-version>
	<service-class>org.diretto.api.client.external.processing.ProcessingServiceImpl</service-class>

	<restlet-client>

		<connector-protocol>HTTP</connector-protocol>

		<!-- http://www.restlet.org/documentation/snapshot/jse/ext/org/restlet/ext/httpclient/HttpClientHelper.html -->

		<connector-parameters>
			<parameter name="followRedirects" value="false" />
			<parameter name="idleCheckInterval" value="0" />
			<parameter name="idleTimeout" value="40000" />
			<parameter name="maxConnectionsPerHost" value="64" />
			<parameter name="maxTotalConnections" value="128" />
			<parameter name="stopIdleTimeout" value="10000" />
			<parameter name="socketTimeout" value="0" />
			<parameter name="tcpNoDelay" value="false" />
		</connector-parameters>

	</restlet-client>

</config>
